### PR TITLE
V3 - allow all symbols by default, set the default min length to 12 instead of 10, fix license filename (fix #78)

### LINKED ISSUE #78: What are the affected if input with wrong symbols
I just want to know what the effect is if I enter the wrong symbol?. I would expect an incorrect symbol to show a warning or error such as an invalid symbol result. I've tried the demo with the space symbol but the results make no difference. Then, what is its function?

### PR DESCRIPTION
**Pull request by Ennoriel**
- allow all symbols by default (any character except the 26 latin lowercase, uppercase letters and 10 digits)
- set the default min length to 12 instead of 10
- fix license filename

@deanilvincent could you please review this PR that allows all symbols by default (fix #78)? I also increased the default minlength since it's quite common to see a minlength of 12 nowadays.

**I did not increase the version in the readme. Since it is a breaking change, it should go to version 3.0.0.**

I also cleaned and simplified the README.

### CODE REVIEW

File: dist/index.mjs [hunk 1]
```diff
@@ -9,81 +9,85 @@ const defaultOptions = [
...
+    },
+    {
+      key: "number",
+      regex: "[0-9]",
     },
     {
-      regex: '[0-9]',
-      message: 'number'
+      key: "symbol",
+      regex: restrictSymbolsTo ? `[${restrictSymbolsTo}]` : "[^a-zA-Z0-9]",
```
Comment (jbrower2) [inline dist/index.mjs:62]: it's not documented that `restrictSymbolsTo` needs to be a valid string for inside a character class in a regular expression. i'd recommend using [`escape-string-regexp`](https://www.npmjs.com/package/escape-string-regexp) here (then cleaning up the string above to get rid of the extra `\`s

Comment (jbrower2) [reply dist/index.mjs:62]: for example, passing `$][&` for `restrictSymbolsTo` would require that the password match `[$][&]`, so the strings `x$x`, `x&x`, and `x&$x` would not match, but `x$&x` would.

Comment (jbrower2) [reply dist/index.mjs:62]: additionally, `,-.` in the `owaspSymbols` string will _technically_ get interpreted as "any character from `,` to `.`" because of the `-`. in reality, the only character between `,` and `.` in the ascii table is `-`, so it's fine, but this feels like a potential bug if the symbols in that string ever get rearranged. (but escaping the string like i laid out above would solve this problem)

Comment (Ennoriel) [reply dist/index.mjs]: You are right. I added the library which is extremely tiny. I added the necessary information in the doc.

**Review by deanilvincent — APPROVED** [review]
Hi @Ennoriel,
Amazing changes! 🥳 🎆  I also tested it on my local and everything seems fine
